include Makefile.specific

OBJS := wrtd-rt-fd.o
OBJS += ../common/loop-queue.o
OUTPUT = wrtd-rt-fd
WRNC = ../../../../

EXTRA_CFLAGS += -I../../include
EXTRA_CFLAGS += -I../common
include $(WRNC)/applications/common/rt/Makefile
