OBJS := wrtd-rt-tdc.o
OBJS += ../common/loop-queue.o
OUTPUT = wrtd-rt-tdc
WRNC = ../../../../

EXTRA_CFLAGS += -I../../include
EXTRA_CFLAGS += -I../common
include $(WRNC)/applications/common/rt/Makefile
